spring:
  application:
    name: edu-simple-gateway
  profiles:
    active: local
  banner:
    location: "classpath:config/app-banner.txt"
app-info:
  build:
    version: '@project.version@'
    timestamp: '@app.build.timestamp@'